loadJoin: true
redis:
  ip: 213.133.102.110
  port: 30090
  pwd: "g1q3684g#$"
  key: "SERVER_UPDATE"
  max: 10

permissions:
  DEFAULT:
    - minelc.default
    - minelc.tell
  PERUANO:
    - minelc.peruano
    - "{heredar: DEFAULT}"
  SVIP:
    - minelc.svip
    - "{heredar: VIP}"
  ELITE:
    - minelc.elite
    - "{heredar: SVIP}"
  RUBY:
    - minelc.ruby
    - "{heredar: ELITE}"
  MOD:
    - minelc.mod
    - "{heredar: AYUDANTE}"
  ADMIN:
    - minelc.admin
    - "{heredar: MOD}"
  OWNER:
    - minelc.owner
    - "{heredar: ADMIN}"